CREATE TABLE pending_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    phone VARCHAR(10) NOT NULL CHECK (phone ~ '^0[0-9]{9}$'),
    address_line VARCHAR(500) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    otp_hash VARCHAR(100) NOT NULL,
    otp_expires_at TIMESTAMPTZ NOT NULL,
    failed_attempts INTEGER NOT NULL DEFAULT 0 CHECK (failed_attempts BETWEEN 0 AND 5),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_pending_registrations_email_normalized
        CHECK (email = lower(btrim(email)))
);
